In [2]:
import numpy as np
import pandas as pd

In [13]:
# Specify the path to your .npy file
train_file_path = 'fashion_train.npy'
test_file_path = 'fashion_test.npy'

# Load the data from the .npy file
data = np.load(train_file_path)
test_data = np.load(test_file_path)
print(data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 3]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]


In [16]:
#convert it to a dataframe
df = pd.DataFrame(data)
test_df = pd.DataFrame(test_data)
# print the first 5 items
print(df.head())

   0    1    2    3    4    5    6    7    8    9    ...  775  776  777  778  \
0    0    0    0    0    0    3    0    0    0   41  ...   63   78   11    0   
1    0    0    0    0    0    0    0    0    0    0  ...   32    0    0    0   
2    0    0    0    0    0    1    1    0    0    0  ...  168  119    0    0   
3    0    0    0    0    0    0    0    0    0   98  ...   21    0    0    0   
4    0    0    0    0    0    0    0    2    0    0  ...   88  128   46    0   

   779  780  781  782  783  784  
0    2    0    0    0    0    0  
1    0    0    0    0    0    1  
2    0    0    0    0    0    0  
3    0    0    0    0    0    3  
4    0    0    0    0    0    4  

[5 rows x 785 columns]


In [17]:
# get the number of rows
num_rows = df.shape[0]
print(num_rows)

10000


In [18]:
# Extract the last column
last_column = data[:, -1]  

In [19]:
# Initialize counts
count_0_tshirt = 0
count_1_trousers = 0
count_2_pull_over = 0
count_3_dress = 0
count_4_shirt = 0


# Loop through the last column
for value in last_column:
    if value == 0:
        count_0_tshirt += 1
    elif value == 1:
        count_1_trousers += 1
    elif value == 2:
        count_2_pull_over += 1
    elif value == 3:
        count_3_dress += 1
    elif value == 4:
        count_4_shirt += 1

# Display the counts
print("Count of 0s:", count_0_tshirt)
print("Count of 1s:", count_1_trousers)
print("Count of 2s:", count_2_pull_over)
print("Count of 3s:", count_3_dress)
print("Count of 4s:", count_4_shirt)

Count of 0s: 2033
Count of 1s: 1947
Count of 2s: 2001
Count of 3s: 2005
Count of 4s: 2014


In [20]:
# Get the simple probabilities


P_tshirt = count_0_tshirt / num_rows
P_trouser = count_1_trousers / num_rows
P_pull_over = count_2_pull_over/ num_rows
P_dress = count_3_dress / num_rows
P_shirt = count_4_shirt / num_rows

print(f" P(T-shirt) = {P_tshirt}")
print(f" P(Trousers) = {P_trouser}")
print(f" P(Pull Over) = {P_pull_over}")
print(f" P(Dress) = {P_dress}")
print(f" P(Shirt) = {P_shirt}")

 P(T-shirt) = 0.2033
 P(Trousers) = 0.1947
 P(Pull Over) = 0.2001
 P(Dress) = 0.2005
 P(Shirt) = 0.2014


In [24]:
import numpy as np
import matplotlib.pyplot as plt

X = df # Replace this with your actual data
y = [0, 1, 2, 3, 4] # Replace this with your actual labels

# Split the data into four classes
class_0_data = X[y == 0][]
class_1_data = X[y == 1]
class_2_data = X[y == 2]
class_3_data = X[y == 3]
class_4_data = X[y == 4]

class_0_data = df[df['label'] == 0].iloc[:, :-1]
class_1_data = df[df['label'] == 1].iloc[:, :-1]
class_2_data = df[df['label'] == 2].iloc[:, :-1]
class_3_data = df[df['label'] == 3].iloc[:, :-1]
class_4_data = df[df['label'] == 4].iloc[:, :-1]

# Define the Gaussian kernel function
def gaussian_kernel(u):
    return (1 / np.sqrt(2 * np.pi)) * np.exp(-0.5 * u**2)

# Define the kernel density estimation function
def kernel_density_estimate(x, data, bandwidth=1.0, kernel=gaussian_kernel):
    n = len(data)
    total = 0
    for xi in data:
        u = (x - xi) / bandwidth
        total += kernel(u)
    return total / (n * bandwidth)

# Function to predict class using Naive Bayes classifier
def naive_bayes_predict(x, class_0_data, class_1_data):
    p_class_0 = kernel_density_estimate(x, class_0_data[:, 0]) * kernel_density_estimate(x, class_0_data[:, 1])
    p_class_1 = kernel_density_estimate(x, class_1_data[:, 0]) * kernel_density_estimate(x, class_1_data[:, 1])
    p_class_2 = kernel_density_estimate(x, class_2_data[:, 0]) * kernel_density_estimate(x, class_2_data[:, 1])
    p_class_3 = kernel_density_estimate(x, class_3_data[:, 0]) * kernel_density_estimate(x, class_3_data[:, 1])
    p_class_4 = kernel_density_estimate(x, class_4_data[:, 0]) * kernel_density_estimate(x, class_4_data[:, 1])

    # Assume equal prior probabilities for all classes
    p_class_0 /= (p_class_0 + p_class_1 + p_class_2 + p_class_3 + p_class_4)
    p_class_1 /= (p_class_0 + p_class_1 + p_class_2 + p_class_3 + p_class_4)
    p_class_2 /= (p_class_0 + p_class_1 + p_class_2 + p_class_3 + p_class_4)
    p_class_3 /= (p_class_0 + p_class_1 + p_class_2 + p_class_3 + p_class_4)
    p_class_4 /= (p_class_0 + p_class_1 + p_class_2 + p_class_3 + p_class_4)

    return np.argmax([p_class_0, p_class_1, p_class_2, p_class_3, p_class_4])

# Make predictions on the test set
X_test = test_data  # Replace this with your actual test data
y_pred = np.array([naive_bayes_predict(x, class_0_data, class_1_data, class_2_data, class_3_data, class_4_data) for x in X_test])

# Plot the results
plt.scatter(class_0_data[:, 0], class_0_data[:, 1], label='Class 0')
plt.scatter(class_1_data[:, 0], class_1_data[:, 1], label='Class 1')
plt.scatter(class_2_data[:, 0], class_2_data[:, 1], label='Class 2')
plt.scatter(class_3_data[:, 0], class_3_data[:, 1], label='Class 3')
plt.scatter(class_4_data[:, 0], class_4_data[:, 1], label='Class 4')
plt.scatter(X_test[:, 0], X_test[:, 1], marker='x', label='Test Data', c=y_pred, cmap='viridis')
plt.legend()
plt.show()


KeyError: False